"""
    BLOCK STRUCTURE FOR BLOCKCHAIN
    Each block is represented by a json file
    - hash (SHA256 hash): hash generated from the JSON representation of a block
"""
import hashlib
import json

class Block():
    def __init__(self, data, root, id, nonce):
        self.data = data
        self.root = root
        self.id = id
        self.nonce = nonce
        self.hash = self.get_hash()
    def generate_string(self):
        """ Generate a string object of the block (to be used for hash)
            JSON is only preference. We can also use Marshal or Pickle
        """
        json_str = json.dumps({"data":self.data, "root":self.root, "nonce":self.nonce})
        return json_str
    def get_hash(self):
        """ Generate hash from the generated byte-encoded object string
        """
        return hashlib.md5(self.generate_string().encode()).hexdigest()
