""" TRANSACTION
    This consists of 3 main things:
    - id: unique id generated by python.uuid
    - w1 is sender, w2 is receiver
"""
import uuid
import json
from wallet import Wallet

class Transaction():
    def __init__(self, w1, w2, amount=None):
        self.id = self.generate_id().hex
        self.output = None
        self.input = Input(w1, self.output)
        return
    
    def generate_id(self):
        return uuid.uuid4()
    
    def verify_transaction(self):
        return
        
class Input():
    def __init__(self, w1, output):
        self.amount = w1.balance
        self.address = w1.pubkey
        self.signature = w1.sign_data(output)
    def to_string(self):
        json_str = json.dumps({"amount":self.amount, "address":self.address, "signature":self.signature})
        return json_str

w1 = Wallet(200)
t = Transaction(w1, w1)
print(w1.balance, w1.pubkey)
print(t.input.amount, t.input.address, t.input.signature)